name: picole
description: "A centralized image board for Artists to share their works!"

publish_to: 'none' 

version: 0.0.1+5

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.1
  uuid: ^4.4.2
  flutter_staggered_grid_view: ^0.7.0
  pocketbase: ^0.10.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  cloudinary_sdk: ^5.0.0+1
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.3
  cached_network_image: ^3.3.1

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios.png"
  image_path_android: "assets/launcher/android.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/launcher/

  fonts:
  - family: Questrial
    fonts:
      - asset: assets/fonts/Questrial.ttf
        weight: 400
